#!/bin/bash

#check for XCode install
xcodeapp="/Applications/Xcode.app"

if [ -e "$xcodeapp" ]
  then
    echo "XCode is already installed, continuing."
  else
    echo "Xcode needs to be installed before installing macports. Exiting setup script."
    exit 0
fi

echo "Agree to Xcode license (needs sudo)"
sudo xcodebuild -license accept

#echo "Installing Command Line Tools"
#`pwd`/misc/install_cmd_line_tools.sh

#echo "Setting Command Line Tools as default (needs sudo)"
#sudo xcode-select --switch "/Library/Developer/CommandLineTools"

echo "Downloading and installing latest macports release (install needs sudo)"
/usr/bin/curl -o /tmp/macports.pkg https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.14-Mojave.pkg 
sudo /usr/sbin/installer -pkg /tmp/macports.pkg -target /

echo "Updating macports definitions (needs sudo)"
sudo /opt/local/bin/port selfupdate
sudo /opt/local/bin/port upgrade outdated

echo "Installing some packages (with dependencies)"
sudo /opt/local/bin/port -N install zsh mosh tmux mas mtr pwgen youtube-dl htop glances

sudo /opt/local/bin/port select --set python python27
sudo /opt/local/bin/port select --set python2 python27

echo "Installing latest iTerm (needs sudo)"

#curl down xml with http links
/usr/bin/curl -s https://www.iterm2.com/appcasts/final.xml |/usr/bin/tail -8 |/usr/bin/grep http >> /tmp/tmp_url_iterm.txt
# get the exact url from that xml
/usr/bin/awk -F'[""]' '{print $2}' /tmp/tmp_url_iterm.txt >> /tmp/dl_url_iterm.txt
# curl down the zip file
/usr/bin/xargs -n 1 /usr/bin/curl -o /tmp/iTerm.zip < /tmp/dl_url_iterm.txt
# unzip the file into /Applications
sudo /usr/bin/unzip -qo -d /Applications /tmp/iTerm.zip
#clean up
/bin/rm -rf /tmp/iTerm.zip
/bin/rm -rf /tmp/tmp_url_iterm.txt
/bin/rm -Rf /tmp/dl_url_iterm.txt

echo "Installing Source Code Pro font"
/usr/bin/curl -o /tmp/source-code-pro.zip https://www.fontsquirrel.com/fonts/download/source-code-pro
/usr/bin/unzip /tmp/source-code-pro.zip -d ~/Library/Fonts/

echo "Installing Oh my ZSH"
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

echo "Installing zsh plugins & theme"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/denysdovhan/spaceship-prompt.git ~/.oh-my-zsh/custom/themes/spaceship-prompt

ln -s ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting.plugin.zsh
ln -s ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions.plugin.zsh
ln -s ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme

echo "Setup configuration files"

rm ~/.zshrc ~/.zshenv ~/.aliases  ~/.gitconfig  ~/.gitignore ~/.spaceship_options ~/.tmux.conf

config_files=`pwd`/config/*

for file in $config_files; do
  config=$(basename $file)
  echo "Creating symlink for .$config"
  ln -s $file ~/.$config
done

echo "Adding zshrc for macports"
ln -s `pwd`/zshrc/zshrc-macports ~/.zshrc

echo "Adding aliases for bins"

mkdir -p ~/bin/
bin_aliases=`pwd`/bins/*

for bins in $bin_aliases; do
  bin=$(basename $bins)
  echo "Creating symlink for $bin"
  ln -s $bins ~/bin/$bin
done

#echo "Setup vim theme"
#mkdir -p ~/.vim/colors
#vim_theme=`pwd`/themes
#ln -s $vim_theme/dracula.vim ~/.vim/colors/dracula.vim

echo "Installing SpaceVim"
curl -sLf https://spacevim.org/install.sh | bash

echo "Setting iTerm2 preferences folder..."
defaults write com.googlecode.iterm2 "PrefsCustomFolder" -string "`pwd`/iterm"
defaults write com.googlecode.iterm2 "LoadPrefsFromCustomFolder" -bool true

echo "Setting brew zsh as default shell (needs sudo)"
sudo sh -c 'echo /opt/local/bin/zsh >>/etc/shells'
sudo chpass -s '/opt/local/bin/zsh' $USER

echo "Setup done"
