#!/bin/bash

echo "Updating apt"
sudo apt update

echo "Installing some apps"
sudo apt install git zsh vim mosh tmux mtr pwgen youtube-dl subnetcalc htop glances -y

echo "Installing Oh my ZSH"
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

echo "Installing zsh plugins & theme"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/denysdovhan/spaceship-prompt.git ~/.oh-my-zsh/custom/themes/spaceship-prompt

ln -s ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting.plugin.zsh
ln -s ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions.plugin.zsh
ln -s ~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme

echo "Setup configuration files"

rm ~/.zshrc ~/.aliases  ~/.gitconfig  ~/.gitignore  ~/.vimrc ~/.spaceship_options ~/.tmux.conf

config_files=`pwd`/config/*

for file in $config_files; do
  config=$(basename $file)
  echo "Creating symlink for .$config"
  ln -s $file ~/.$config
done

echo "Setup vim theme"

mkdir -p ~/.vim/colors
vim_theme=`pwd`/themes
ln -s $vim_theme/dracula.vim ~/.vim/colors/dracula.vim

echo "Setup done."
