#!/bin/bash

echo "Updating apt"
sudo apt update

echo "Installing some apps"
sudo apt install zsh mosh tmux mtr pwgen youtube-dl subnetcalc htop glances -y

echo "Installing Oh my ZSH"
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

echo "Default shell to zsh"
chsh -s /bin/zsh

echo "Installing zsh plugins"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/plugins/zsh-autosuggestions

echo "Setup configuration files"

rm ~/.zshrc ~/.aliases  ~/.gitconfig  ~/.gitignore  ~/.vimrc

config_files=~/git/psaintemarie/dotfiles/config/*

for file in $config_files; do
  config=$(basename $file)
  echo "Creating symlink for .$config"
  ln -s $file ~/.$config
done

echo "Setup done."
